# Generated by Django 2.1.2 on 2018-11-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_house',
            name='Feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='Rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='double_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='double_wa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='floorbed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='single_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='single_wa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='triple_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_house',
            name='triple_wa',
            field=models.IntegerField(null=True),
        ),
    ]
