# Generated by Django 2.1.2 on 2018-11-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20181117_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_hostel',
            name='bed_type',
        ),
        migrations.DeleteModel(
            name='Bed_Type',
        ),
    ]
