# Generated by Django 2.1.2 on 2018-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='refrence_Amenities',
            fields=[
                ('am_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenities', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='avg_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='gallery',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='guest',
            field=models.IntegerField(null=True),
        ),
    ]
