# Generated by Django 2.1.3 on 2018-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_pages2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='gallery1',
            field=models.URLField(blank=True, default=-1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='gallery2',
            field=models.URLField(blank=True, default=-1.0),
            preserve_default=False,
        ),
    ]
