# Generated by Django 2.1.3 on 2018-12-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_pages2', '0002_auto_20181201_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('am_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pics', models.URLField()),
            ],
        ),
    ]
