# Generated by Django 2.1.3 on 2018-12-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_pages2', '0003_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
    ]
