# Generated by Django 2.1.3 on 2018-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_pages2', '0008_auto_20181208_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
